version: 0.2
phases:
  pre_build:
    commands:
      - echo "[+] Running tests..."
      - python test_lambda_function.py
  install:
    commands:
      - aws cloudformation deploy --stack-name restapi-workflow-stack --template file://./lambda_workflow.yml --parameter-overrides file://./params.json --tags file://./tags.json --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM
      - aws cloudformation deploy --template /path_to_template/my-template.json --stack-name my-new-stack --parameter-overrides Key1=Value1 Key2=Value2
      - aws cloudformation package --template-file template.yml --s3-bucket mysandbox-ramiaj-lambda-bucket --output-template-file packaged.yml
artifacts:
  files:
    - template.yml
    - packaged.yml
